# Generated by Django 4.1.1 on 2022-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_slug'),
        ('photos', '0002_create_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tagged_pets',
            field=models.ManyToManyField(null=True, to='pets.pet'),
        ),
    ]
